apiVersion: v1
kind: Service
metadata:
  name: futurae-service
  namespace: futurae
spec:
  selector:
    app: futurae
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
